let shopItemData = [{
    id: "fhgfjhfsk",
    name: "Jesus Acrylic Painting for Christmas Decoration",
    price: 100,
    desc: "This painting is made with acrylic paint. This is amazing paint for home decore and Christmas decor. This picture shows Jesus make people walk on water.",
    img: "images/VIPERAJONES - HELENA.jfif",
    size: "8 x 10 (inches)",
},
{
    id: "dnhrgjfv",
    name: "Assassins Creed Valaha Painting",
    price: 90,
    desc: "This is Assassins creed character painting. This is made with acrylic colours.",
    img: "images/IMG_20220628_151923923.jpg",
    size: "8 x 10 (inches)",
},{
    id: "nfehfjehs",
    name: "Viola Assassins creed painting",
    price: 100,
    desc: "This is Assassins creed character painting. This is made with acrylic colours.",
    img: "images/IMG_20220628_173435482.jpg",
    size: "8 x 10 (inches)",
},{
    id: "nfhfjskss",
    name: "Witch Painting",
    price: 100,
    desc: "This painting is made with acrylic paint. This is amazing paint for home decore and Christmas decor.",
    img: "images/IMG_20220628_102746490.jpg",
    size: "8 x 10 (inches)",
}];